### ISSUE TITLE
UserListNode.h 질문드립니다

### ISSUE THREAD

**Issue by chanseobx** [DSLDataStorage/DS_Project_1_2021_2#15]
큐에서 pop하면 list에 인서트하고 Bst에 인서트 하는걸로 생각하고 있습니다.

1.UserListnode.h에 있는InsertAccount 함수의 정의를 안해도 구현이 될것 같은데 상관없나요?

2. InsertAccount 함수 인자가 bst노드, 반환값도 bst노드이던데 어떤걸 생각하시고 만드셨는지 알 수 있을까요?

3. 스켈레톤코드에 있는 함수를 필요에 따라 정의 해도 되나요?

**Comment by DSLDataStorage** [comment]
1. 제공된 함수를 사용안하셔도 됩니다. 다만, 함수는 그대로 나두세요.
2. bst와 userlist를 연결하기 위한 반환 값입니다.
3. 제공된 함수 및 변수는 나두고 추가는 필요에 따라 더 하셔도 됩니다.
