### ISSUE TITLE
Makefile에 질문 있습니다.

### ISSUE THREAD

**Issue by quad0214** [DSLDataStorage/DS_Project_1_2021_2#16]
Makefile의 SURC에 *.h로 컴파일에 헤더 파일이 포함되기에 컴파일 시간이 많이 소모되는 것 같습니다.
인터넷에 검색해본 결과 g++의 인자로 헤더는 포함 안 하는 것 같아, SURC의 *.h를 제외하고 컴파일 한 결과 컴파일 속도가 개선되었고, 코드들도 제대로 링크되는 것 같았습니다. 

 이에 makefile의 SURC에서 *.h 부분을 제외하고 사용해도 되는지 궁금합니다.

**Comment by DSLDataStorage** [comment]
사용해도 되지만 채점은 제공된 파일로 할 예정입니다.
