### ISSUE TITLE
UserHeapNode.h 질문드립니다.

### ISSUE THREAD

**Issue by chanseobx** [DSLDataStorage/DS_Project_1_2021_2#20]
1. Number변수는 Id가 아니라 user를 카운팅하는게 맞나요?
2. SetNumber() 함수의 용도는 무엇인가요? Number를 증감하는 연산 용도라면 매개변수가 존재하는 이유가 무엇인가요? 아니라면 어떤 용도인지 설명 부탁드립니다. 매개변수가 무엇을 의미하는지 궁금합니다.

**Comment by DSLDataStorage** [comment]
1. 예 해당 연령대에 속한 유저 수에 관한 변수입니다.
2. 증감에 따라 1 또는 -1이 들어갈 수 있기 때문에 매개변수가 존재합니다. 사용은 안하셔도 됩니다.
