### ISSUE TITLE
BST delete 구현시 질문

### ISSUE THREAD

**Issue by chanseobx** [DSLDataStorage/DS_Project_1_2021_2#29]
BST delete 구현시 노드 자체를 변경하라고 수정하신 것 같은데 이렇게 해도 괜찮나요?
예를 들어 계정을 삭제해야 하는 BST노드의 위치를 대체할 대체노드를 찾습니다. 삭제해야할 데이터를 대체노드의 대이터로 덮어씌웁니다.  그 다음 삭제노드, 대체노드 UserList를 재구성하고 대체노드를 삭제합니다. 이렇게 해도 괜찮을까요?

**Comment by DSLDataStorage** [comment]
해당 방법은 노드를 교환하는 방법이 아닌 데이터만 바꾸는 방법입니다.
BST의 노드 자체를 교환해야 하므로 노드의 정보를 변경 시키지 말고 포인터들을 수정하여 위치를 조정하셔야 합니다.
