### ISSUE TITLE
UserHeap에 질문 있습니다.

### ISSUE THREAD

**Issue by quad0214** [DSLDataStorage/DS_Project_1_2021_2#44]
HLOAD 명령을 진행하는 경우 UserHeap이 이미 존재하면 이를 제거하고 다시 생성한다고 제안서에 작성되어있습니다. 이에 기존의 UserHeap 객체의 메모리를 소멸 시킨 후에 다시 동적할당해도 되는 지 궁금합니다.
  
 이와 관련된 다른 질문들에는 UserHeap의 노드를 제거하는 방식에 대한 것만 있어, 이 방법도 가능 한지 궁금합니다.

**Comment by DSLDataStorage** [comment]
네 자유롭게 구현하시면 됩니다.
